const [formData, setFormData] = useState({
    SName: "",
    SPhone: "",
    SAddress: "",
    SEmail: "",
    RName: "",
    RPhone: "",
    RAddress: "",
    REmail: "",
    TShipment: "",
    Packages: "",
    Product: "",
    PMode: "",
    Carrier: "",
    DTime: "",
    Destination: "",
    Comments: "",
    Mode: "",
    CarrierRef: "",
    Origin: "",
    DDate: "",
  })